// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxadruguovzvrvwqajfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWRydWd1b3Z6dnJ2d3FhamZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzcyMTMsImV4cCI6MjA2MzkxMzIxM30.vpehcNhj4ayY3ynFjcibWfLSL58p3TJE5QyEEhUltaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);